apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: motivation-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Afraazzz/argocd.git
    targetRevision: HEAD
    path: helmchart
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
